version: '1.0'
name: pipeline-management_system
displayName: pipeline-management_system
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: stage-d9b8043f
    displayName: 打包
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-87ddd5d4
    displayName: 推送到服务器
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: aliyun-server
          hostID:
            - a60aa108-c0db-4dd2-9d74-751728d4bb2f
        deployArtifact:
          - source: artifact
            name: output
            target: ~/gitee_go/deploy
            artifactRepository: default
            artifactName: output
            artifactVersion: latest
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - 'mkdir -p /home/my-project/management_system # 新建目录'
          - rm -rf /home/my-project/management_system/*
          - 'tar zxvf ~/gitee_go/deploy/output.tar.gz -C /home/my-project/management_system # 解压'
          - 'chmod -R 777 /home/my-project/management_system # 设置目录访问权限，防止nginx访问403'
          - '# sh /home/admin/app/deploy.sh restart'
          - '# 如果你是php之类的无需制品包的制品方式，可以使用 git clone 或者 git pull 将源代码更新到服务器，再执行其他命令'
          - '# git clone ***@***.git'
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
